version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'news_habit'
      MYSQL_USER: 'crawl_user'
      MYSQL_PASSWORD: 'crawl1234'
      MYSQL_ROOT_PASSWORD: 'root1234'
      TZ: 'Asia/Seoul'
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/custom.cnf

  spring-app:
    build:
      context: ./newsHabit
      dockerfile: dockerfile
    restart:
      on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/news_habit?useUnicode=true&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: "crawl_user"
      SPRING_DATASOURCE_PASSWORD: "crawl1234"
      TZ: "Asia/Seoul"
    depends_on:
      - mysql

  python-app:
    build:
      context: ./crawling
      dockerfile: Dockerfile
    environment:
      TZ: "Asia/Seoul"
    command: python3 ./src/main.py
    depends_on:
      - mysql

volumes:
  db-data: